# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres
    container_name: postgresdb
    restart: always
    ports:
      - 54032:5432
    environment:
      POSTGRES_PASSWORD: mypass
    volumes:
      - ./mnt-pnt:/home/root/mnt-pnt
