version: '3.1'

services:
  db:
    image: mariadb:latest
    container_name: wp-db
    # restart: always
    ports:
      - 33006:3306
    environment:
      MYSQL_ROOT_PASSWORD: passwd
      MYSQL_DATABASE: wpdb
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: passwd
    volumes:
      - data_db:/var/lib/mysql

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    container_name: wp-app
    #restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: passwd
      WORDPRESS_DB_NAME: wpdb
    volumes:
      - wordpress:/var/www/html
volumes:
  wordpress:
  db:
