version: '3.1'

services:
  wordpress:
    image: wordpress
    container_name: wordpress-app
    #restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: dbuser
      WORDPRESS_DB_PASSWORD: passwd
      WORDPRESS_DB_NAME: wpdb
    volumes:
      - wordpress:/var/www/html

  db:
    image: mariadb:latest
    container_name: wordpress-db
    # restart: always
    environment:
      MYSQL_DATABASE: wpdb
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: passwd
      MYSQL_ROOT_PASSWORD: passwd
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db:
