# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mariadb
    container_name: mariadb
    restart: always
    ports:
      - 33006:3306
    environment:
      MYSQL_ROOT_PASSWORD: mypass
      # MYSQL_DATABASE: mydb
      # MYSQL_USER: myuser
      # MYSQL_PASSWORD: mypass
    volumes:
      - ./mnt-pnt:/home/root/mnt-pnt
