version: '3'

services:
    database:
      container_name: ${DB_CONTAINER_NAME}
      image: mariadb:${DB_IMAGE_TAG}
      restart: always
      command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
      volumes:
        - ${LOCAL_DB_DIR}:/var/lib/mysql
      environment:
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    application:
      depends_on:
        - database
      container_name: ${APP_CONTAINER_NAME}
      image: nextcloud:${APP_IMAGE_TAG}
      restart: always
      ports:
         - 8080:80
      volumes:
         - ${LOCAL_DATA_DIR}:/var/www/html
         - ${LOCAL_CONF_DIR}:/var/www/html/config
         - ${LOCAL_APPS_DIR}:/var/www/html/apps
      environment:
        NEXTCLOUD_ADMIN_USER: ${NEXTCLOUD_ADMIN_USER}
        NEXTCLOUD_ADMIN_PASSWORD: ${NEXTCLOUD_ADMIN_PASSWORD}
        NEXTCLOUD_DATA_DIR: ${NEXTCLOUD_DATA_DIR}
        NEXTCLOUD_TABLE_PREFIX: ${NEXTCLOUD_TABLE_PREFIX}
        NEXTCLOUD_TRUSTED_DOMAINS: ${NEXTCLOUD_TRUSTED_DOMAINS}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        MYSQL_HOST: ${MYSQL_HOST}
      links:
        - database
